SELECT TOP 1000 [ProductID]
      ,[Name]
      ,[ProductNumber]
      ,[Color]
      ,[SafetyStockLevel]
      ,[ReorderPoint]
      ,[StandardCost]
      ,[ListPrice]
      ,[ModifiedDate]
  FROM [AdventureWorks].[Production].[Product]